#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from dynamic_training_controller.controller.interface import Interface

plugin = 'dynamic_training_controller'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
