#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from omniroute_controller.omniroute_controller_interface import Interface

plugin = 'omniroute_controller'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
