#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from omniroute_interface.interface import Interface

plugin = 'omniroute_interface'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
