#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from pseudorandom_control.pseudorandom_control_interface import Interface

plugin = 'pseudorandom_control'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
