#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from single_T_maze.single_T_maze_interface import Interface

plugin = 'single_T_maze'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
