#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from three_by_three_interface.interface import Interface

plugin = 'three_by_three_interface'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
